### ISSUE TITLE
No mapping for identifier <Space.Application.Injector> was found

### ISSUE THREAD

**Issue by zimt28** [CodeAdventure/space-ui#13]
I tried space-ui on my codebase using a second branch and everything worked fine. I now wanted to start from scratch instead of merging the code, as I know some things I'd like to improve and restructure. However, I don't know what this error is about. I can post some of my code if it helps :)

```
[Error] Error: No mapping for identifier <Space.Application.Injector> was found.
	get (space_base.js, line 152)
	injectInto (space_base.js, line 163)
	injectInto (space_base.js, line 164)
	initialize (space_base.js, line 336)
	initialize (space_base.js, line 430)
	Application (space_base.js, line 426)
	Application (application.coffee.js, line 9)
	(anonymous function) (app.js, line 68)
	runStartupCallbacks (meteor.js, line 784)
	ready (meteor.js, line 786)
```

**Comment by DominikGuzei** [comment]
Sorry, I didn't post it anywhere: The newest `space:base` package releases I am mapping the injector simply as `Injector` and not `Space.Application.Injector`

Which versions are you using? And please post some code :-)

**Comment by zimt28** [comment]
space:base@1.2.0 and
space:ui@3.4.0
 
But I'm not using `Space.Application.Injector` directly somewhere, maybe it has to be updated in `space:ui`? Will do that later, still have some questions :)

**Comment by DominikGuzei** [comment]
please try upgrading to `space:base@1.2.1`, that's the latest version :-)

**Comment by DominikGuzei** [comment]
but to be safe, you can also downgrade to `space:base@1.1.0` which definitely works with `space:ui@3.4.0` I will check out the possible issue between the latest versions.

**Comment by zimt28** [comment]
Just updated, same error. For 1.1.0 and 1.2.1 /:

**Comment by DominikGuzei** [comment]
Ok I found the problem, it's totally my fault – I didn't think about breaking the API. But of course `space-ui` happily updates to the 1.2 releases of `space:base` because they *should* be compatible :-)

I found the problem and will fix it ASAP!

**Comment by DominikGuzei** [comment]
@zimt28 Please try `space:ui@3.4.2`, the problem should be fixed :-)

**Comment by DominikGuzei** [comment]
By the way, what do you think about the updated documentation of [space:base](https://github.com/CodeAdventure/meteor-space)?

**Comment by zimt28** [comment]
Not it says  `[Error] Error: A mapping for <Meteor> already exists`. I like the new docs, but have to take some more time to really get into it :) I'll also create a single application for now and maybe later split it into modules (just learned space lets me do that :D)

**Comment by zimt28** [comment]
Works now, I added lines for Session and Meteor as well, but they seem to be available by default (Y)

**Comment by DominikGuzei** [comment]
Ok, great! So with a single application it works, but with app + module it throws that error?

**Comment by zimt28** [comment]
It throws that error when I add `@injector.map('Meteor').toStaticValue Meteor` to the Space.Application, as that's already included :)

**Comment by DominikGuzei** [comment]
Ah ok, that's a feature :-) so everything works as expected now?
`Space.Application` maps the complete Meteor api by default. So you can access everything like `Meteor`, `EJSON`, `check` etc. and even `Email` and `Accounts` if you load the respective core-packages!
