### ISSUE TITLE
Using store.getState('key') also reruns the reactive context when another key has changed

### ISSUE THREAD

**Issue by Sanjo** [CodeAdventure/space-ui#19]
This behavior has already annoyed me several times since I use space:ui (3 weeks). I suggest that each state key is a separate ReactiveVar. So that the reactive context is only rerun when a dependency on a state key changes. Until now I've never used getState() without a key ;-)

**Comment by DominikGuzei** [comment]
True, I had this on my todo list for several months – I think now is a good time to implement it! :+1:

**Comment by DominikGuzei** [comment]
Ok, I am in the middle of implementing this but I it actually isn't that simple. There are many edge cases where memory leaks and problems with overriding nested reactive vars can occur. I am not so sure if this is actually a good idea. Also I see no one who has implemented this before, could be a strong indicator that it *is* problematic.

**Comment by Sanjo** [comment]
Are you trying to implement this for any key depth (e.g. state.key.subkey) or just the top level keys (state.key)?
I think doing this for the top level keys is the most useful.

**Comment by Sanjo** [comment]
It's definitely a optimization. The current behavior is ok when Blaze or React is used because they only change what is necessary for rendering.

But in my app I have an autorun block that modifies the UI directly (in my case the Ace editor). This autorun block only depends on one state key. But it is executed quiet often because other state changes.

**Comment by DominikGuzei** [comment]
Yeah, its mostly optimization – sounds great in theory but is hell if you want to implement it cleanly without introducing memory leaks in your system. I will post the code I came up with here and if you want to take on the challenge, you can continue and make a pull request when there is full test coverage :wink:

I don't think that only making the top level properties reactive vars is good idea, it would be a very strange way to define a half-baked API.

Here is the basic code to make nested reactive vars work, but as I said its very easy to introduce memory leaks by  overriding nested properties:

```coffeescript
class Space.ui.ReactiveObject

  _root: null

  constructor: -> @_root = new ReactiveVar {}

  get: (path) ->
    if not path?
      @_root.get()
    else
      @_getNestedProperty(path).get()

  set: (path, value) ->
    if not value?
      value = path
      @_root.set value
    else
      @_getNestedProperty(path, true).set value

  _getNestedProperty: (path) ->
    pathArray = path.split '.'
    property = @_root

    for key in pathArray
      value = Tracker.nonreactive -> property.get()
      next = value[key]
      isReactiveVar = next? and (next instanceof ReactiveVar)

      if !isReactiveVar
        value[key] = new ReactiveVar({})
        property.set value
        property = value[key]
      else
        property = value[key]

    return property
```

Here are the unit tests for it:

```coffeescript
{ReactiveObject} = Space.ui

describe 'Space.ui.ReactiveObject', ->

  beforeEach -> @object = new ReactiveObject()

  it 'should be empty by default', ->
    expect(@object.get()).to.deep.equal {}

  it 'can be set as a whole', ->
    value = {}
    @object.set value
    expect(@object.get()).to.equal value

  it 'provides reactive access', ->
    result = null
    value = {}
    computation = Tracker.autorun => result = @object.get()
    @object.set value
    Tracker.flush()
    computation.stop()
    expect(result).to.equal.value

  it 'allows to set nested vars', ->
    value = {}
    @object.set 'my.nested.value', value
    expect(@object.get 'my.nested.value').to.equal value

  it 'allows to subscribe to non-existing vars', ->
    spy = sinon.spy()
    computation = Tracker.autorun => spy @object.get('my.nested.var')
    @object.set 'my.nested.var', 'test'
    Tracker.flush()
    computation.stop()
    expect(spy).to.have.been.calledWithExactly 'test'

  it 'provides fine grained nested reactivity', ->

    firstSpy = sinon.spy()
    secondSpy = sinon.spy()
    @object.set 'my.nested.first', 'first'
    @object.set 'my.nested.second', 'second'

    computation1 = Tracker.autorun => firstSpy @object.get 'my.nested.first'
    computation2 = Tracker.autorun => secondSpy @object.get 'my.nested.second'

    @object.set 'my.nested.first', 'changed'
    Tracker.flush()

    computation1.stop()
    computation2.stop()

    expect(firstSpy).to.have.been.calledTwice
    expect(secondSpy).to.have.been.calledOnce
```

**Comment by Sanjo** [comment]
I think the right way to do it is to create Tracker.Dependency objects on the fly when store.get is used and manage them in a hash (key -> Tracker.Dependency). https://github.com/meteor/meteor/blob/devel/packages/reactive-dict/reactive-dict.js is basically doing this. Just the nested keys as argument of get and set is missing.

I can have a try with this tomorrow.

**Comment by DominikGuzei** [comment]
Ok great, looking forward to this solution :+1: would be really awesome! I don't have the patience to get this done at the moment!

**Comment by Sanjo** [comment]
I'm 30% done with the implementation. It's going to be a separate package reactive-nested-dict that space-ui can just use. I use reactive-dict as a base.

Don't know exactly when I have time to finish it, but I think in the next four weeks.

**Comment by DominikGuzei** [comment]
Awesome! I also think it will be better as standalone package, since this will also be interesting for others who are not using `space:ui` :+1:

**Comment by DominikGuzei** [comment]
Hey @Sanjo, how is the implementation going on?

**Comment by Sanjo** [comment]
I didn't have time yet to continue working on it, but it's still on my todo list.

I could make a pull-request that just make the top level properties reactive separately earlier. That could use the default implementation of ReactiveDict.

**Comment by DominikGuzei** [comment]
Yeah, I think that might be enough for most cases but avoids the complex nesting of reactive vars which is problematic in regard to memory leaks and also often not what you want in practice (e.g i often like to set a whole object to be the new state)

**Comment by DominikGuzei** [comment]
Hey @Sanjo, in version `4.3.2` I introduced the concept of setting non-reactive default state which solves part of the problem for me. You can use the new `setDefaultState` method for that, which isn't reactive. This is specially useful for all default values in your stores and mediators, that should only be set once on startup but not override the current values if any other dependency changed.
