### ISSUE TITLE
Using store.setState(key, value) reruns the reactive context when the state changes.

### ISSUE THREAD

**Issue by Sanjo** [CodeAdventure/space-ui#20]
I expect that `store.setState(key, value)` does not establish a reactive dependency to the state.
I think you can wrap https://github.com/CodeAdventure/space-ui/blob/master/source/store.coffee#L29 with `Tracker.nonreactive` to fix this.

**Comment by DominikGuzei** [comment]
Thanks for the bug report – this definitely should be fixed!
