### ISSUE TITLE
backward compatibility/ final api

### ISSUE THREAD

**Issue by zimt28** [CodeAdventure/space-ui#22]
Hey there :)
I just updated space-ui to find out there are a lot of new things
I like the new way of handling events and the new Space.ui.Application - things are much cleaner, nice!

However, the new version breaks backward compatibility. It is not documented and there is no guide on how to migrate from older versions. I'm wondering when there'll be a stable api, so that such radical api changes won't happen anymore (in the major version)?

As you might have guessed I have some questions ;) 

- Events and helpers are not defined in the mediator anymore, right? It took me some time migrating to this concept and there are cases where I use data from the store in my helpers. How could this work? Going back to regular helpers and events to seems like adding another layer, which I'd like to prevent. Maybe we could keep helpers and events in the mediator. Thoughts?
- I still have all my mediators and controllers on an `App` namespace. This seems not supported by the new Space.ui.Application, unless I map all controllers and collections manually or override the run method.

I'd love to know what you think before trying to move to the newest version of space-ui, as it seems to be quite some work /:  You seem to be experimenting with new ideas to find out what's the best way to do things, and I like that. But I'm using space-ui in production and it's really hard to get up to date.

Thanks :)

**Comment by zimt28** [comment]
One thing I forgot about backward compatibility: It would be nice if the older api still worked, so that users have some versions to adopt the new concepts. We could do it step by step instead of having to rearrange so much code at once. Older apis could then be dropped at new major versions or so :)

**Comment by rhyslbw** [comment]
What version were you running @zimt28 ?

**Comment by zimt28** [comment]
@rhyslbw 3.4.4

**Comment by DominikGuzei** [comment]
Hey @zimt28,
Sorry for the inconveniences I caused you – I know that it would have been more graceful to keep old APIs and upgrade step by step. Also, I think this will remain more or less the "stable" API for the next months from which I'd like to build up more concepts as use cases arise.

Let me explain why introduced the changes in version 4:

* **The new messaging**: I used this system on the server side for several months now and it works much better than the string based dispatcher / action messaging from flux. Meteors `Match` and `check` are very powerful and flexible to give your message a runtime-checked structure (the `@fields` property on events and commands). `EJSON` is also very awesome, but only if you have some automation going on for you. So this is basically what `Space.messaging.Serializable` is all about, you tell it what fields your instance expects and then it can be automatically serialized and sent to the server as JSON + rebuilt on the server side with (again) runtime-checks :wink:

* **Removed template helpers and events from mediators**: This was an ugly hack from the beginning on and actually goes against what mediators should be concerned of. Mediators should only talk to the views via a very well defined view-API or the other way round. The `templateHelpers` method was moving view-related concerns into the mediator where they don't belong. It also destroys the abstraction of the view framework. Today it is `Blaze` that we want to use, but maybe tomorrow you want to switch to `React.js` for your rendering. So only `TemplateMediatorMap` should be concerned about these differences (how to map a view to a mediator) but not the mediator and view itself.

**Comment by DominikGuzei** [comment]
And I will try to update the documentation as soon as possible, currently I have too much todo with my production app to do these time intensive maintenance tasks :disappointed: and there are two more important packages which lack documentation (`space:messaging` and `space:cqrs`).

**Comment by DominikGuzei** [comment]
@zimt28 I updated the main README to reflect the latest version :wink: 
Also you can take another look at the TodoMVC example, there was a non-breaking update to space:messaging that makes the event handling syntax a bit sweeter!
