### ISSUE TITLE
Related thread on Meteor Forums - MeteorFlux Flow

### ISSUE THREAD

**Issue by rhyslbw** [CodeAdventure/space-ui#25]
just a headsup on this thread over at https://forums.meteor.com/t/meteorflux-flow/920/35

Feel free to close this off, I just thought it would be worth checking out since Space UI has been mentioned. Seems like a good chance to highlight the features of Space, or provide some insight that had been overlooked

**Comment by DominikGuzei** [comment]
Thanks for the link! I posted something there, explaining why having good messaging contracts is important in real-world applications instead of string-based action dispatching with plain objects :wink:

**Comment by rhyslbw** [comment]
:+1:
