### ISSUE TITLE
Error on startup: Cannot read property 'constructor' of undefined

### ISSUE THREAD

**Issue by npvn** [CodeAdventure/space-ui#26]
I'm refactoring an existing app to use space-ui.

This error happens on client startup. My browser console points to line `56` of `space:messaging/source/controller.coffee`:

```coffeescript
  @_isEvent: (message) ->
    message.__super__.constructor is Space.messaging.Event
```

I've been investigating for a long time without any clue :pensive:

Here is the refactored app:
https://bitbucket.org/npvn/meteor-url-shortener/commits/branch/space-ui

Any help is greatly appreciated!

**Comment by DominikGuzei** [comment]
Hey @npvn!
This error indicates that you try to publish something on the `Space.messaging.EventBus` that is not extending the `Space.messaging.Event` class. Currently you can only publish events, but the next version of space:messaging will be more flexible. I already have it on my computer and will push it today!

**Comment by npvn** [comment]
@DominikGuzei: Thanks for the quick reply!

You gave me a clue that eventually led me to discovering the bug: It's a [syntax error](https://bitbucket.org/npvn/meteor-url-shortener/commits/42422b7043c525340151014cdae20e15c22276b2?at=space-ui) :satisfied:

Thanks again!

**Comment by DominikGuzei** [comment]
You are welcome! :wink:
