### ISSUE TITLE
Mediator cannot be defined in Blaze Components template

### ISSUE THREAD

**Issue by npvn** [CodeAdventure/space-ui#27]
Hi @DominikGuzei,

I'm experimenting using [Blaze Components](https://github.com/peerlibrary/meteor-blaze-components) with space-ui.

Everything has been working well, except that I cannot define mediator for a template if that template is registered as Blaze Component.

Specifically, the `UrlFormMediator` [here](https://bitbucket.org/npvn/meteor-url-shortener/src/69887bc108f5959e3f30bf390257d5cb19700417/client/views/components/url_form/?at=space-ui-blaze-components) is not defined inside `UrlForm` template instances.

It looks like Blaze Components has interfered with the way mediator is initiated. Do you have any idea of a work-around?

**Comment by Sanjo** [comment]
A workaround could be to not use the Mediator of Space UI at all. Instead you can make the Blaze Component injectable. I have done this with Meteor Templates (via Mixin).

**Comment by Sanjo** [comment]
Here is how I have done it for Meteor templates:

```javascript
Template.dependenciesMixin.hooks({
  created: function () {
    // Support Dependencies on template
    this.Dependencies = this.view.template.Dependencies;
    Simian.App.injector.injectInto(this);
  }
});
```

You can adjust that for Blaze Components I think. `Simian.App` is the Space UI app instance.

**Comment by DominikGuzei** [comment]
Hey guys,
Cool – I also used the blaze-components library and really like it!

@npvn I use the two libraries differently:

- blaze-components is superb for encapsulated components that don't know where they get their data from. So i treat them like any other Blaze template, but can provide properties etc. from outside.
- space:ui remains the high-level framework that prepares and fetches the data and hands it off to individual blaze-components. So you can think of it like blaze-components = React, space:ui = Flux

If you really want to use them together, you have to take a look at how blaze-components injects itself into the template lifecycles. space:ui does so in a very non-destructive manner, but if blaze-components overrides the template hooks (created, rendered etc.) afterwards, then its a problem.

**Comment by npvn** [comment]
Thanks for your suggestions.

Actually I'm following the same approach like what @DominikGuzei mentioned: I use space-ui to orchestrate how data flows inside the app, and use a component framework to create dumb, composable views.

I'm experimenting with the 3 available component frameworks (Flow Components, Blaze Components and React) to see which one works best with space-ui.

If you're interested, feel free to join me [here](https://github.com/npvn/meteor-url-shortener/branches/all) :wink:

**Comment by Sanjo** [comment]
> I'm experimenting with the 3 available component frameworks (Flow Components, Blaze Components and React) to see which one works best with space-ui.

Great. I'm interested in the results.

Right now I just use Meteor Templates with https://github.com/aldeed/meteor-template-extension because I think the Meteor Core should set a standard for UI Components so the whole community can use the same thing. I also think that the upcoming additions to Meteor Templates will make them more useful out of the box.

**Comment by DominikGuzei** [comment]
Is this still a real issue or should we close it?

**Comment by npvn** [comment]
@DominikGuzei: It's still an issue. I haven't had time to work on it yet.

**Comment by DominikGuzei** [comment]
Ok, @npvn I will take some time today and look over your examples! :wink:
your https://github.com/npvn/meteor-url-shortener repo looks awesome, you want to share some more experiences how integration with react and flow-components worked?

**Comment by DominikGuzei** [comment]
Hey @npvn,
I looked into your issue it seems to be a bug in `blaze-components` that "normal" Blaze template hooks don't work correctly anymore after making it a component.

I filed an issue here: https://github.com/peerlibrary/meteor-blaze-components/issues/53

**Comment by DominikGuzei** [comment]
Closing this issue as it is not a problem with `space:ui` but `blaze-components` which does not stick to the standards and thus makes integration pretty hard.

**Comment by mitar** [comment]
I think that you should do this as @Sanjo is describing. And this is by creating a mixin for Blaze Components:

```coffee
class DependenciesMixin extends BlazeComponent
    onCreated: ->
      Simian.App.injector.injectInto @mixinParent()
 ```

Or something. I have no idea how this Space UI thingy works. :-)

**Comment by DominikGuzei** [comment]
Yeah I think for now the best solutions are either:
1. Create high-level Blaze templates that are connected with a mediator and distribute the data down to the sub-templates and blaze-components
2. Ignore the `Space.ui.Mediator` and do the dependency injection yourself with a blaze-component mixin.

**Comment by mitar** [comment]
Also, I think there could be much better integration by creating a common class. You could do (untested):

```coffee
class BlazeComponentsMediator extends Space.ui.Mediator
  template: ->
    # To use Mediator's class-level field.
    @constructor.Template

# Make BlazeComponentsMediator into a Blaze Component as well.
for property, value of BlazeComponent when property not in ['__super__',]
  IronBlazeComponent[property] = value
for property, value of (BlazeComponent::) when property not in ['constructor']
  IronBlazeComponent::[property] = value
```

No idea if that works. But something alongside this direction I think would be the correct way to do it. So to extend Mediator so that you do not have to use templates anymore, but can use directly Blaze Components.

Then you can do:

```coffee
class @TodoListMediator extends BlazeComponentsMediator

  @Template: 'todo_list'

  Dependencies:
    store: 'TodosStore'
    meteor: 'Meteor'

  setDefaultState: -> editingTodoId: null

  setInitialState: ->
    todos: @store.get('todos')
    hasAnyTodos: @store.get('todos').count() > 0
    allTodosCompleted: @store.get('activeTodos').count() is 0

  toggleTodo: (todo) -> @publish new TodoToggled todoId: todo._id

  deleteTodo: (todo) -> @publish new TodoDeleted todoId: todo._id

  editTodo: (todo) -> @set 'editingTodoId', todo._id

  submitNewTitle: (todo, newTitle) ->
    @publish new TodoTitleChanged todoId: todo._id, newTitle: newTitle
    @stopEditing()

  toggleAllTodos: -> @meteor.call 'toggleAllTodos'

  stopEditing: -> @set 'editingTodoId', null

  state: -> @getState()

  isToggleChecked: ->
    # This probably should not be accessing .state(), but something else?
    if @state().hasAnyTodos and @state().allTodosCompleted then 'checked' else false

  prepareTodoData: ->
    @state().isEditing = @get('editingTodoId') is @data()._id
    return @data()

  events: ->
    super.concat
      'toggled .todo': (event) -> @toggleTodo @

      'destroyed .todo': (event) -> @deleteTodo @

      'doubleClicked .todo': (event) -> @editTodo @

      'editingCanceled .todo': -> @stopEditing()

      'editingCompleted .todo': (event) ->
        newTitle = @getTitleValue()
        @submitNewTitle @data(), newTitle

      'click #toggle-all': -> @toggleAllTodos()
```

**Comment by mitar** [comment]
I think a lot of patching templates to work with `Mediator` is something Blaze Components are doing as well. So the question is which one should be doing what when you combine things like this.

**Comment by DominikGuzei** [comment]
Thanks @mitar this looks pretty cool!
I will try it out and if it works well I could just add a `Space.ui.BlazeComponent` that could work similar to your example :wink:

**Comment by mitar** [comment]
BTW, how does `setInitialState` work? Reactively? Why is then initial state?

**Comment by DominikGuzei** [comment]
Yeah, that's not perfect :wink: it is reactive, so it probably would be better named to `setReactiveState` or something. There is also `setDefaultState` which is not reactive.

**Comment by DominikGuzei** [comment]
@npvn, @mitar, @Sanjo I am happy to announce full (optional) integration of `blaze-components` in `space:ui@5.1.0` :smile: 

There is a new class `Space.ui.BlazeComponent` that provides full support of both APIs:
```coffeescript
class @FooterComponent extends Space.ui.BlazeComponent

  @register 'footer'

  Dependencies:
    store: 'TodosStore'
    meteor: 'Meteor'

  setDefaultState: -> availableFilters: @_mapAvailableFilters()

  setReactiveState: ->
    activeTodosCount: @store.get('activeTodos').count()
    completedTodosCount: @store.get('completedTodos').count()

  pluralize: (count) -> if count is 1 then 'item' else 'items'

  events: -> [
    'click #clear-completed': (event) -> @meteor.call 'clearCompletedTodos'
  ]

  _mapAvailableFilters: -> _.map @store.FILTERS, (key) ->
    name: key[0].toUpperCase() + key.slice 1
    path: key
```

all you have todo (extra) is to tell your application or module to setup the components:

```coffeescript
class @TodoMVC extends Space.ui.Application
  // …
  Components: ['InputComponent', 'FooterComponent']
  // …
```

Really love this integration because it brings together two really useful packages!

**Comment by npvn** [comment]
@DominikGuzei: This is very awesome! Thank you :+1: 

About your question, here is my experience after trying out the 3 component solutions (React, Blaze Components and Flow Components) with space-ui:

=====

*Flow Components*

A component framework in its early stage. Its API is not yet polished. The framework has some significant limitations (see below).

Pros:

- Built on top of Blaze and thus have access to the power of Meteor templates.

Cons:

- Technically we cannot create stateless components. See the comment marked with "XXX Flow Components Comment 1" in the [space-ui-flow-components](https://github.com/npvn/meteor-url-shortener/tree/space-ui-flow-components) branch.

- Sometimes we will need to create redundant states. See "XXX Flow Components Comment 2".

- Passing an event handler from a parent component to its children is very cumbersome. See  "XXX Flow Components Comment 3".

=====

*React*

A framework with a simple, straightforward and predictable API. Writing app with React feels weird at first, but the more I use it, the more I like it.

However, the integration between React and space-ui at the moment is not streamlined. Many times I needed to change the structure of the app or apply workarounds to get it to work. See the comments marked with "XXX React Comment" in the [space-ui-react](https://github.com/npvn/meteor-url-shortener/tree/space-ui-react) branch.

Pros:

- Simple but powerful API.

- Huge support from the community and a rapidly growing ecosystem.

Cons:

- Without templating, we lose many great things that come with Blaze. But this might be different in the future. Evan and Avital at MDG are working on a [promising experiment] (https://github.com/meteor/meteor/tree/experimental-spacebars-over-react).

- There's no established pattern for using React with Meteor (and space-ui). We may have to come up with a lot of workarounds.

=====

*Blaze Components*

A well-designed framework with clear and easy to use API.

Its only limitation was the conflict with space-ui. But now that we've solved this problem, Blaze Components looks like the most well-rounded solution :).

=====

*Conclusion*

Both Blaze Components and React are potential options.

For a short-term choice, Blaze Components is great with very well-designed API and the ability to work seamlessly with Blaze.

For a long-term consideration, React is incomparable with its huge community and ecosystem.

**Comment by DominikGuzei** [comment]
Hey @npvn, thanks for your great research work, really appreciate that! :wink: 
I also really like React and used it for other projects, however for Prisma (my only Meteor app) I don't use it atm and switching would be too costly. But if you want to try, it should be pretty easy to bridge the gap to `space:ui` and make more pleasant API – look at the blaze-components integration, that's only a few lines of code.

The only thing I don't like so much about React is its size – its around 40kb gzipped although its only the rendering layer and you need jQuery in many cases too … not to mention the supporting code to integrate it with your meteor app.

Another reason for me to stay away from React is that the core team is under high pressure to release a better component framework, so I see blaze-components more like a temporary solution.

**Comment by romanzolotarev** [comment]
@npvn Thanks for sharing your research!
