### ISSUE TITLE
Update to use space:base@2.0.0?

### ISSUE THREAD

**Issue by Sanjo** [CodeAdventure/space-ui#28]
Would be nice. Thanks.

**Comment by DominikGuzei** [comment]
Just pushed version 5.0.0 which updates to `space:base@2.0.0` and `space:messaging@1.0.0` – be aware of the breaking changes in both packages!

Especially for `space:messaging`, I changed the way how to communicated between client-server. `Space.messaging.CommandBus` on the client does not send the commands to the server anymore. There is the new `Space.messaging.Api` to define Meteor methods that can be tested easily (they are defined as instance methods on the api object too) and which are integrated into the space environment (so you can use injection etc.) :wink:

**Comment by Sanjo** [comment]
Cool. I have skipped version 4.x ;-) I'm transitioning from 3.4.3 to 5.x right now.

**Comment by DominikGuzei** [comment]
Haha, nice :wink: let me know if you have any questions. I will try to put together some documentation for `space:messaging` over the weekend.
