### ISSUE TITLE
Improve APIs and debugging when working in Javascript

### ISSUE THREAD

**Issue by DominikGuzei** [CodeAdventure/space-ui#32]
A lot of the APIs in space where inspired by the possibilities of Coffeescript. In some parts, it became quite ugly to write the same functionality in Javascript. To get more people on board it is definitely important that writing Space applications in Javascript should be equally awesome :wink:

Here are some key areas where improvements are needed:

## Extending classes
In Coffeescript we have `class Test extends Other` which gives us good debugging in browser consoles. The space framework provies `Space.Object.extend` which also gives a lot of power to Javascript, but unfortunately creates a lot of anonymous `_Class`, because it is based on the coffeescript inheritance.
To solve this problem, an advanced API is necessary that is able to create named classes and assign them to namespaces etc. (in work)

## Static methods (meta-programming)
One of the nicest parts of Coffeescript is the static meta-programming and the Space framework is heavily based on this sugar. However, it is not as nice in Javascript and sometimes leads to quite bloated code that could be much simpler. (in work)

**Comment by DominikGuzei** [comment]
I am happy to announce that all of the above mentioned problems have been fixed in the latest releases :smile:

**Comment by rhyslbw** [comment]
Great job!
