### ISSUE TITLE
Reflux

### ISSUE THREAD

**Issue by zimt28** [CodeAdventure/space-ui#8]
Sorry for creating all the issues but I'd love to learn this as your code just looks too nice and clean :)
Have you seen [Reflux](https://github.com/spoike/refluxjs)? It's based on facebook's flux but gets rid of the dispatcher and seems to be easier to understand.

See
- http://blog.krawaller.se/posts/react-js-architecture-flux-vs-reflux/
- http://blog.krawaller.se/posts/reflux-refinement
- http://spoike.ghost.io/deconstructing-reactjss-flux/

By the way: will you maintain this package or is it going to stay as-is and die slowly? Just asking because this happens to quite some packages ..

**Comment by zimt28** [comment]
Hey! That looks great, thank you :) Looks like it's time now to start switching to this solution, just have to figure out the best approach :D But I think I will just convert simple pages first and then go on to the more complex ones.

**Comment by DominikGuzei** [comment]
Glad you like it, you were right – it's much nicer that way! I already refactored my code in my Prisma app too :-)
